apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-nginx
  name: eks-nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: eks-nginx
  template:
    metadata:
      labels:
        app: eks-nginx
    spec:
      containers:
      - image: 779547665473.dkr.ecr.ap-northeast-2.amazonaws.com/ecr_nginx:6a8ea41
        name: eks-nginx























